//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int IdMessages { get; set; }
        public Nullable<int> IdUser { get; set; }
        public string MesContent { get; set; }
        public Nullable<System.DateTime> TimesTamp { get; set; }
    
        public virtual User User { get; set; }
    }
}
